//! Its own test binary: it overrides `PATH` process-wide.
#![cfg(unix)]

mod common;

use std::fs;
use std::path::Path;

const CARGO_LOCK: &str = "\
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"shared\"
version = \"1.0.0\"
";
const ROOT_MANIFEST: &str = "[workspace]\nmembers = [\"crates/*\"]\nresolver = \"2\"\n\
     \n[workspace.package]\nversion = \"1.0.0\"\n\
     \n[workspace.dependencies]\nshared = { path = \"crates/shared\", version = \"1.0.0\" }\n";
const NPM_MANIFEST: &str = r#"{"name":"shared","version":"2.0.0"}"#;

/// The crate inherits its version from `[workspace.package]`, so a release rewrites the root
/// manifest; only `Cargo.lock` is committed, so only the cargo gate can fire.
fn write_colliding_workspace(root: &Path) {
    fs::write(root.join("Cargo.toml"), ROOT_MANIFEST).unwrap();
    fs::create_dir_all(root.join("crates/shared/src")).unwrap();
    fs::write(
        root.join("crates/shared/Cargo.toml"),
        "[package]\nname = \"shared\"\nversion.workspace = true\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/shared/src/lib.rs"), "").unwrap();
    fs::write(root.join("Cargo.lock"), CARGO_LOCK).unwrap();

    fs::write(
        root.join("package.json"),
        r#"{"name":"root","private":true,"workspaces":["packages/*"]}"#,
    )
    .unwrap();
    fs::create_dir_all(root.join("packages/shared")).unwrap();
    fs::write(root.join("packages/shared/package.json"), NPM_MANIFEST).unwrap();

    fs::create_dir_all(root.join(".sampo/changesets")).unwrap();
    fs::write(
        root.join(".sampo/config.toml"),
        "[git]\nrelease_branches = [\"main\"]\n",
    )
    .unwrap();
    fs::write(
        root.join(".sampo/changesets/c.md"),
        "---\nnpm/shared: minor\n---\n\nfeat: an npm-only change\n",
    )
    .unwrap();
}

#[test]
fn a_shared_name_pulls_the_other_ecosystem_into_the_gate() {
    let temp = tempfile::tempdir().unwrap();
    let root = temp.path();
    write_colliding_workspace(root);
    let _guard = common::use_only(&root.join("empty-bin"));

    let err = sampo_core::run_release(root, false)
        .expect_err("the release can write the root cargo manifest, so cargo is needed");
    let message = err.to_string();
    assert!(
        message.contains("cargo") && message.contains("PATH"),
        "blocked on the cargo toolchain: {message}"
    );

    assert_eq!(
        fs::read_to_string(root.join("Cargo.toml")).unwrap(),
        ROOT_MANIFEST,
        "the root manifest must be untouched"
    );
    assert_eq!(
        fs::read_to_string(root.join("Cargo.lock")).unwrap(),
        CARGO_LOCK,
        "the lockfile must be untouched"
    );
    assert_eq!(
        fs::read_to_string(root.join("packages/shared/package.json")).unwrap(),
        NPM_MANIFEST,
        "the npm manifest must be untouched"
    );
}
