blank_issues_enabled: false
contact_links:
  - name: Any ideas or suggestions?
    url: https://github.com/bruits/sampo/discussions/categories/ideas
    about: Propose and discuss future improvements to Sampo.
  - name: Support or help needed?
    url: https://github.com/bruits/sampo/discussions/categories/q-a
    about: Ask questions and get help from the community.
