blank_issues_enabled: false
contact_links:
  - name: Questions, support, or chat?
    url: https://discord.com/invite/84pd4QtmzA
    about: Join the Bruits Discord to ask questions and chat with the community.
