[package]
name = "sampo-github-action"
version = "0.0.0"
edition = "2024"
license = "MIT"
description = "GitHub Action runner for Sampo CLI (release/publish orchestrator)"
readme = "README.md"
repository = "https://github.com/bruits/sampo"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "1.0"

[dev-dependencies]
tempfile = "3.0"
