use crate::errors::{Result, SampoError, WorkspaceError};
use crate::process::command;
use crate::types::{PackageInfo, PackageKind};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use toml_edit::DocumentMut;

use super::{
    GLEAM_MANIFEST, compute_requirement, format_command_display, has_flag, normalize_path,
};

/// Gleam's lockfile, regenerated by `gleam deps download`.
const GLEAM_LOCKFILE: &str = "manifest.toml";

/// Gleam has no workspace/members manifest, so a monorepo is just several
/// directories each carrying their own `gleam.toml`. We scan for them, bounded in
/// depth to stay cheap on unrelated repos and to avoid descending into build output
/// or downloaded dependencies.
const MAX_SCAN_DEPTH: usize = 4;

pub(super) fn can_discover(root: &Path) -> bool {
    !find_manifests(root).is_empty()
}

pub(super) fn discover(root: &Path) -> std::result::Result<Vec<PackageInfo>, WorkspaceError> {
    let mut name_to_path: BTreeMap<String, PathBuf> = BTreeMap::new();
    let mut normalized_to_name: BTreeMap<PathBuf, String> = BTreeMap::new();
    let mut parsed = Vec::new();

    for manifest_path in find_manifests(root) {
        let dir = manifest_path
            .parent()
            .map(Path::to_path_buf)
            .unwrap_or_else(|| root.to_path_buf());
        let text = fs::read_to_string(&manifest_path).map_err(|e| {
            WorkspaceError::Io(crate::errors::io_error_with_path(e, &manifest_path))
        })?;
        let doc = parse_toml(&text).ok_or_else(|| {
            WorkspaceError::InvalidManifest(format!("invalid TOML in {}", manifest_path.display()))
        })?;
        let Some(name) = string_field(&doc, "name") else {
            return Err(WorkspaceError::InvalidManifest(format!(
                "missing package name in {}",
                manifest_path.display()
            )));
        };
        let version = string_field(&doc, "version").unwrap_or_default();
        let deps = collect_dependencies(&doc, &dir);

        name_to_path.insert(name.clone(), dir.clone());
        normalized_to_name.insert(normalize_path(&dir), name.clone());
        parsed.push((name, version, dir, deps));
    }

    let mut packages = Vec::new();
    for (name, version, dir, deps) in parsed {
        let identifier = PackageInfo::dependency_identifier(PackageKind::Hex, &name);
        let mut internal = BTreeSet::new();

        for dep in deps {
            if let Some(path) = &dep.path {
                let normalized = normalize_path(path);
                if let Some(dep_name) = normalized_to_name.get(&normalized) {
                    internal.insert(PackageInfo::dependency_identifier(
                        PackageKind::Hex,
                        dep_name,
                    ));
                    continue;
                }
            }
            // Only registry (version-string) or path deps can name-match a workspace
            // member; a git dep that merely shares a name is not an internal link.
            if (dep.requirement.is_some() || dep.path.is_some())
                && name_to_path.contains_key(&dep.name)
            {
                internal.insert(PackageInfo::dependency_identifier(
                    PackageKind::Hex,
                    &dep.name,
                ));
            }
        }

        packages.push(PackageInfo {
            name,
            identifier,
            version,
            path: dir,
            internal_deps: internal,
            internal_dev_deps: BTreeSet::new(),
            kind: PackageKind::Hex,
        });
    }

    Ok(packages)
}

pub(super) fn manifest_path(package_dir: &Path) -> PathBuf {
    package_dir.join(GLEAM_MANIFEST)
}

pub(super) fn is_publishable(manifest_path: &Path) -> Result<bool> {
    let text = fs::read_to_string(manifest_path)
        .map_err(|e| SampoError::Io(crate::errors::io_error_with_path(e, manifest_path)))?;
    let doc = parse_toml(&text).ok_or_else(|| {
        SampoError::Publish(format!(
            "Manifest {} is not valid TOML",
            manifest_path.display()
        ))
    })?;

    let name = string_field(&doc, "name");
    if name.as_deref().map(str::trim).unwrap_or("").is_empty() {
        return Err(SampoError::Publish(format!(
            "Manifest {} is missing a name field",
            manifest_path.display()
        )));
    }

    let version = string_field(&doc, "version");
    if version.as_deref().map(str::trim).unwrap_or("").is_empty() {
        return Err(SampoError::Publish(format!(
            "Manifest {} is missing a version field",
            manifest_path.display()
        )));
    }

    // Gleam has no per-package "private" flag; any well-formed package is publishable.
    Ok(true)
}

pub(super) fn publish(manifest_path: &Path, dry_run: bool, extra_args: &[String]) -> Result<()> {
    let manifest_dir = manifest_path.parent().ok_or_else(|| {
        SampoError::Publish(format!(
            "Manifest {} does not have a parent directory",
            manifest_path.display()
        ))
    })?;

    let mut cmd = command("gleam");
    cmd.current_dir(manifest_dir);

    if dry_run {
        // `gleam publish` has no dry-run flag; building the Hex tarball validates the
        // same artifact the real publish would upload, without touching the registry.
        cmd.arg("export").arg("hex-tarball");
    } else {
        cmd.arg("publish");
        if !has_flag(extra_args, "--yes") && !has_flag(extra_args, "-y") {
            cmd.arg("--yes");
        }
        // Gleam reads HEXPM_API_KEY straight from the environment; Sampo does not pass it.
        if !extra_args.is_empty() {
            cmd.args(extra_args);
        }
    }

    println!("Running: {}", format_command_display(&cmd));

    let status = cmd.status().map_err(|err| {
        if err.kind() == std::io::ErrorKind::NotFound {
            SampoError::Publish(
                "gleam not found in PATH; ensure Gleam is installed to publish packages"
                    .to_string(),
            )
        } else {
            SampoError::Io(err)
        }
    })?;
    if !status.success() {
        let action = if dry_run {
            "gleam export hex-tarball"
        } else {
            "gleam publish"
        };
        return Err(SampoError::Publish(format!(
            "{} failed for {} with status {}",
            action,
            manifest_path.display(),
            status
        )));
    }

    Ok(())
}

pub(super) fn regenerate_lockfile(workspace_root: &Path) -> Result<()> {
    // Each Gleam package owns its `manifest.toml`; refresh every one that already
    // exists. Like the other adapters, we never create a lockfile the user has not
    // generated yet by running gleam.
    for manifest_path in find_manifests(workspace_root) {
        let dir = match manifest_path.parent() {
            Some(dir) => dir,
            None => continue,
        };
        if !dir.join(GLEAM_LOCKFILE).exists() {
            continue;
        }

        println!("Regenerating {} using gleam…", GLEAM_LOCKFILE);
        let mut cmd = command("gleam");
        cmd.arg("deps").arg("download").current_dir(dir);
        println!("Running: {}", format_command_display(&cmd));

        let status = cmd.status().map_err(|err| {
            if err.kind() == std::io::ErrorKind::NotFound {
                SampoError::Release(
                    "gleam command not found; install Gleam to regenerate manifest.toml"
                        .to_string(),
                )
            } else {
                SampoError::Io(err)
            }
        })?;

        if !status.success() {
            return Err(SampoError::Release(format!(
                "gleam deps download failed in {} with status {}",
                dir.display(),
                status
            )));
        }
    }

    Ok(())
}

pub(super) fn update_manifest_versions(
    manifest_path: &Path,
    input: &str,
    new_pkg_version: Option<&str>,
    new_version_by_name: &BTreeMap<String, String>,
) -> Result<(String, Vec<(String, String)>)> {
    let mut doc = input.parse::<DocumentMut>().map_err(|err| {
        SampoError::Release(format!(
            "Manifest {} is not valid TOML: {}",
            manifest_path.display(),
            err
        ))
    })?;

    let mut changed = false;

    if let Some(target_version) = new_pkg_version
        && let Some(item) = doc.get_mut("version")
    {
        let needs_update = item
            .as_str()
            .is_some_and(|current| current != target_version);
        if needs_update {
            *item = toml_edit::value(target_version);
            changed = true;
        }
    }

    let mut updated_deps: BTreeSet<String> = BTreeSet::new();
    for table_name in DEPENDENCY_TABLES {
        let Some(table) = doc
            .get_mut(table_name)
            .and_then(|item| item.as_table_like_mut())
        else {
            continue;
        };
        // Collect names first to avoid holding a mutable borrow while iterating.
        let names: Vec<String> = table.iter().map(|(k, _)| k.to_string()).collect();
        for name in names {
            let Some(new_version) = new_version_by_name.get(&name) else {
                continue;
            };
            let Some(item) = table.get_mut(name.as_str()) else {
                continue;
            };
            // Only string requirements carry a version; path/git deps are tables.
            let Some(current) = item.as_str().map(str::to_string) else {
                continue;
            };
            if let Some(new_spec) = compute_requirement(&current, new_version)
                && new_spec != current
            {
                *item = toml_edit::value(new_spec);
                updated_deps.insert(name);
                changed = true;
            }
        }
    }

    if !changed {
        return Ok((input.to_string(), Vec::new()));
    }

    let applied = updated_deps
        .into_iter()
        .filter_map(|name| {
            new_version_by_name
                .get(&name)
                .cloned()
                .map(|version| (name, version))
        })
        .collect();

    Ok((doc.to_string(), applied))
}

pub(super) fn find_dependency_constraint_value(
    manifest_path: &Path,
    dep_name: &str,
) -> Result<Option<String>> {
    let text = fs::read_to_string(manifest_path)
        .map_err(|e| SampoError::Io(crate::errors::io_error_with_path(e, manifest_path)))?;
    let Some(doc) = parse_toml(&text) else {
        return Ok(None);
    };
    let dir = manifest_path.parent().unwrap_or(Path::new("."));
    for dep in collect_dependencies(&doc, dir) {
        if dep.name == dep_name {
            return Ok(dep.requirement);
        }
    }
    Ok(None)
}

// The hyphen form mirrors Gleam's own dev-dependencies alias, so any manifest Gleam accepts reads the same here.
const DEPENDENCY_TABLES: [&str; 3] = ["dependencies", "dev_dependencies", "dev-dependencies"];

struct ParsedDependency {
    name: String,
    requirement: Option<String>,
    path: Option<PathBuf>,
}

fn parse_toml(text: &str) -> Option<toml::Value> {
    toml::from_str::<toml::Value>(text).ok()
}

fn string_field(doc: &toml::Value, key: &str) -> Option<String> {
    doc.get(key)
        .and_then(toml::Value::as_str)
        .map(str::to_string)
}

fn collect_dependencies(doc: &toml::Value, manifest_dir: &Path) -> Vec<ParsedDependency> {
    let mut deps = Vec::new();
    for table_name in DEPENDENCY_TABLES {
        let Some(table) = doc.get(table_name).and_then(toml::Value::as_table) else {
            continue;
        };
        for (name, value) in table {
            let (requirement, path) = match value {
                toml::Value::String(req) => (Some(req.clone()), None),
                // Local path deps carry no registry version to bump.
                toml::Value::Table(t) => {
                    let path = t
                        .get("path")
                        .and_then(toml::Value::as_str)
                        .map(|p| manifest_dir.join(p));
                    (None, path)
                }
                _ => (None, None),
            };
            deps.push(ParsedDependency {
                name: name.clone(),
                requirement,
                path,
            });
        }
    }
    deps
}

fn find_manifests(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    collect_manifests(root, 0, &mut out);
    out.sort();
    out
}

fn collect_manifests(dir: &Path, depth: usize, out: &mut Vec<PathBuf>) {
    if depth > MAX_SCAN_DEPTH {
        return;
    }
    let manifest = dir.join(GLEAM_MANIFEST);
    // A directory carrying both manifests is a Mix project that also holds Gleam
    // sources (the mix_gleam interop): Mix owns its identity and publish path, so the
    // Gleam scan skips it to avoid discovering the same package twice.
    if manifest.is_file() && !dir.join("mix.exs").exists() {
        out.push(manifest);
    }
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        if is_excluded_dir(&path) {
            continue;
        }
        collect_manifests(&path, depth + 1, out);
    }
}

/// Skip Gleam/BEAM build output, downloaded dependencies, and hidden directories so
/// the scan stays cheap and never treats vendored manifests as workspace members.
fn is_excluded_dir(path: &Path) -> bool {
    match path.file_name().and_then(|n| n.to_str()) {
        Some(name) => {
            name.starts_with('.')
                || matches!(
                    name,
                    "build" | "_build" | "deps" | "node_modules" | "target"
                )
        }
        None => true,
    }
}

#[cfg(test)]
mod gleam_tests;
