use crate::errors::{Result, SampoError, WorkspaceError};
use crate::process::command;
use crate::types::{PackageInfo, PackageKind};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use super::{format_command_display, has_flag};
use tree_sitter::{Language, Node, Parser, Tree};

/// Holds `{deps, [...]}` at the application root; umbrella sub-apps may not carry a copy.
const REBAR_CONFIG: &str = "rebar.config";

/// `src/<name>.app.src` is the authoritative manifest (name + version), and the only
/// file every app is guaranteed to have — unlike `rebar.config`, which umbrella members
/// may omit.
const APP_SRC_SUFFIX: &str = ".app.src";

/// Bound the recursive scan so it stays cheap on unrelated repos and never descends
/// into build output or fetched dependencies.
const MAX_SCAN_DEPTH: usize = 4;

pub(super) fn can_discover(root: &Path) -> bool {
    !find_app_srcs(root).is_empty()
}

/// Whether `package_dir` is an Erlang application root, i.e. it holds a `src/<name>.app.src`.
pub(super) fn has_app_src(package_dir: &Path) -> bool {
    find_app_src(package_dir).is_some()
}

pub(super) fn discover(root: &Path) -> std::result::Result<Vec<PackageInfo>, WorkspaceError> {
    struct Member {
        name: String,
        version: String,
        app_root: PathBuf,
        applications: Vec<String>,
    }

    let mut members: Vec<Member> = Vec::new();
    let mut member_names: BTreeSet<String> = BTreeSet::new();

    for app_src in find_app_srcs(root) {
        // `<app_root>/src/<name>.app.src` → the application root is the grandparent.
        let app_root = app_src
            .parent()
            .and_then(Path::parent)
            .map(Path::to_path_buf)
            .unwrap_or_else(|| root.to_path_buf());

        let text = fs::read_to_string(&app_src)
            .map_err(|e| WorkspaceError::Io(crate::errors::io_error_with_path(e, &app_src)))?;
        let app = parse_app_src(&text).ok_or_else(|| {
            WorkspaceError::InvalidManifest(format!(
                "invalid application resource in {}",
                app_src.display()
            ))
        })?;

        // A `.app.src.script` recomputes the metadata at build time, so any static
        // version we might read (or write) is moot. Treat it like a dynamic version.
        if script_sibling_exists(&app_src) {
            warn_skip(
                &app.name,
                &app_src,
                "its metadata is generated by a .app.src.script",
            );
            continue;
        }

        // Sampo can only manage a version that is a literal string it can bump; git-derived
        // and build-template versions have no static value, so we skip them with guidance.
        let version = match app.version {
            AppVersion::Static(v) if !v.trim().is_empty() => v,
            AppVersion::Static(_) => {
                warn_skip(&app.name, &app_src, "its `vsn` is empty");
                continue;
            }
            AppVersion::Dynamic(reason) => {
                warn_skip(&app.name, &app_src, reason);
                continue;
            }
            AppVersion::Absent => {
                warn_skip(&app.name, &app_src, "it declares no `vsn`");
                continue;
            }
        };

        member_names.insert(app.name.clone());
        members.push(Member {
            name: app.name,
            version,
            app_root,
            applications: app.applications,
        });
    }

    let mut packages = Vec::new();
    for member in members {
        // OTP applications declare inter-app dependencies in their `applications` list;
        // any entry naming another workspace member is an internal dependency. (Sibling
        // apps are referenced as bare atoms, without a version requirement.)
        let mut internal = BTreeSet::new();
        for app in &member.applications {
            if app != &member.name && member_names.contains(app) {
                internal.insert(PackageInfo::dependency_identifier(PackageKind::Hex, app));
            }
        }

        packages.push(PackageInfo {
            identifier: PackageInfo::dependency_identifier(PackageKind::Hex, &member.name),
            name: member.name,
            version: member.version,
            path: member.app_root,
            internal_deps: internal,
            internal_dev_deps: BTreeSet::new(),
            kind: PackageKind::Hex,
        });
    }

    Ok(packages)
}

pub(super) fn manifest_path(package_dir: &Path) -> PathBuf {
    find_app_src(package_dir).unwrap_or_else(|| {
        // Unreachable for discovered packages (discovery found the file). Fall back to
        // the rebar3 convention `src/<appname>.app.src`, where the app name matches the
        // directory name.
        let name = package_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("app");
        package_dir.join("src").join(format!("{name}.app.src"))
    })
}

pub(super) fn is_publishable(manifest_path: &Path) -> Result<bool> {
    let text = fs::read_to_string(manifest_path)
        .map_err(|e| SampoError::Io(crate::errors::io_error_with_path(e, manifest_path)))?;
    let app = parse_app_src(&text).ok_or_else(|| {
        SampoError::Publish(format!(
            "Manifest {} is not a valid Erlang application resource",
            manifest_path.display()
        ))
    })?;

    if app.name.trim().is_empty() {
        return Err(SampoError::Publish(format!(
            "Manifest {} is missing an application name",
            manifest_path.display()
        )));
    }

    match app.version {
        AppVersion::Static(v) if !v.trim().is_empty() => Ok(true),
        AppVersion::Static(_) | AppVersion::Absent => Err(SampoError::Publish(format!(
            "Manifest {} is missing a version field",
            manifest_path.display()
        ))),
        // Discovery already skips dynamic-version packages, so this is defensive.
        AppVersion::Dynamic(reason) => Err(SampoError::Publish(format!(
            "Manifest {} cannot be published because {}",
            manifest_path.display(),
            reason
        ))),
    }
}

pub(super) fn publish(manifest_path: &Path, dry_run: bool, extra_args: &[String]) -> Result<()> {
    // Publishing runs from the application root (the `.app.src` lives under `src/`).
    let app_root = manifest_path
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| {
            SampoError::Publish(format!(
                "Manifest {} is not under an application `src/` directory",
                manifest_path.display()
            ))
        })?;

    let mut cmd = command("rebar3");
    cmd.current_dir(app_root);
    cmd.arg("hex").arg("publish");

    if dry_run {
        // rebar3_hex has a real dry run: it builds and validates the tarball but stops
        // before uploading. Guard against a duplicate if the user also forwards it.
        if !has_flag(extra_args, "--dry-run") {
            cmd.arg("--dry-run");
        }
    } else if !has_flag(extra_args, "--yes") && !has_flag(extra_args, "-y") {
        cmd.arg("--yes");
    }

    // rebar3_hex reads HEX_API_KEY straight from the environment; Sampo does not pass it.
    if !extra_args.is_empty() {
        cmd.args(extra_args);
    }

    println!("Running: {}", format_command_display(&cmd));

    let status = cmd.status().map_err(|err| {
        if err.kind() == std::io::ErrorKind::NotFound {
            SampoError::Publish(
                "rebar3 not found in PATH; ensure rebar3 (with the rebar3_hex plugin) is \
                 installed to publish packages"
                    .to_string(),
            )
        } else {
            SampoError::Io(err)
        }
    })?;

    if !status.success() {
        return Err(SampoError::Publish(format!(
            "rebar3 hex publish failed for {} with status {}",
            manifest_path.display(),
            status
        )));
    }

    Ok(())
}

pub(super) fn update_manifest_versions(
    manifest_path: &Path,
    input: &str,
    new_pkg_version: Option<&str>,
    _new_version_by_name: &BTreeMap<String, String>,
) -> Result<(String, Vec<(String, String)>)> {
    // Only the package's own `vsn` lives in the `.app.src`; internal deps are bare atoms
    // with no version requirement, so `new_version_by_name` has nothing to rewrite.
    let Some(target_version) = new_pkg_version else {
        return Ok((input.to_string(), Vec::new()));
    };

    let literal = locate_vsn_string(input).ok_or_else(|| {
        SampoError::Release(format!(
            "Manifest {} has no static `vsn` string to update",
            manifest_path.display()
        ))
    })?;

    if literal.value == target_version {
        return Ok((input.to_string(), Vec::new()));
    }

    // Splice only the version literal's byte span, leaving every comment and the rest of
    // the terms byte-for-byte untouched.
    let mut output = input.to_string();
    output.replace_range(literal.start..literal.end, &format!("\"{target_version}\""));
    Ok((output, Vec::new()))
}

pub(super) fn find_dependency_constraint_value(
    manifest_path: &Path,
    dep_name: &str,
) -> Result<Option<String>> {
    // External requirements live in `rebar.config` at the application root; internal
    // umbrella deps are bare atoms with no requirement, so they resolve to `None`.
    let Some(app_root) = manifest_path.parent().and_then(Path::parent) else {
        return Ok(None);
    };
    let Ok(text) = fs::read_to_string(app_root.join(REBAR_CONFIG)) else {
        return Ok(None);
    };
    for dep in parse_rebar_deps(&text) {
        if dep.name == dep_name {
            return Ok(dep.requirement);
        }
    }
    Ok(None)
}

/// The version declared by an application's `vsn` key.
enum AppVersion {
    /// A literal string Sampo can read and bump, e.g. `{vsn, "1.2.3"}`.
    Static(String),
    /// A version computed at build time (`{vsn, git}`, `{vsn, "%VSN%"}`, …). The string
    /// explains why it cannot be managed, phrased for a user-facing warning.
    Dynamic(&'static str),
    /// No `vsn` key at all.
    Absent,
}

struct ParsedAppSrc {
    name: String,
    version: AppVersion,
    /// Names from the `applications` list, used to link internal workspace deps.
    applications: Vec<String>,
}

struct StringLiteral {
    /// Byte offset of the opening quote.
    start: usize,
    /// Byte offset just past the closing quote.
    end: usize,
    /// Content between the quotes.
    value: String,
}

struct ParsedDependency {
    name: String,
    requirement: Option<String>,
}

fn erlang_language() -> &'static Language {
    static LANGUAGE: OnceLock<Language> = OnceLock::new();
    LANGUAGE.get_or_init(|| tree_sitter_erlang::LANGUAGE.into())
}

fn parse_erlang(source: &str) -> Option<Tree> {
    let mut parser = Parser::new();
    parser.set_language(erlang_language()).ok()?;
    parser.parse(source, None)
}

/// The named children of `node` (skips anonymous tokens like `{`, `,`, `.`).
fn named_children<'tree>(node: Node<'tree>) -> Vec<Node<'tree>> {
    let mut cursor = node.walk();
    node.named_children(&mut cursor).collect()
}

/// The top-level Erlang terms of a file: each `{...}.` form is a `tuple` that is a
/// direct named child of the root, so nested tuples are never mistaken for forms.
fn top_level_tuples(tree: &Tree) -> Vec<Node<'_>> {
    named_children(tree.root_node())
        .into_iter()
        .filter(|n| n.kind() == "tuple")
        .collect()
}

/// The unquoted text of an `atom` node, e.g. `vsn`, or `Foo` for the quoted atom `'Foo'`.
fn atom_text(node: Node, source: &str) -> Option<String> {
    if node.kind() != "atom" {
        return None;
    }
    let text = source.get(node.start_byte()..node.end_byte())?;
    let unquoted = text
        .strip_prefix('\'')
        .and_then(|t| t.strip_suffix('\''))
        .unwrap_or(text);
    Some(unquoted.to_string())
}

/// The content and byte span of a `string` node. Erlang strings are a single token whose
/// span includes both double quotes, so the value is simply the interior slice.
fn string_literal(node: Node, source: &str) -> Option<StringLiteral> {
    if node.kind() != "string" {
        return None;
    }
    let start = node.start_byte();
    let end = node.end_byte();
    let text = source.get(start..end)?;
    if text.len() < 2 || !text.starts_with('"') || !text.ends_with('"') {
        return None;
    }
    Some(StringLiteral {
        start,
        end,
        value: source.get(start + 1..end - 1)?.to_string(),
    })
}

/// Find the `{application, Name, [Props]}` form and read its name, version, and
/// `applications` list.
fn parse_app_src(source: &str) -> Option<ParsedAppSrc> {
    let tree = parse_erlang(source)?;
    for tuple in top_level_tuples(&tree) {
        let elems = named_children(tuple);
        if elems.len() < 3 || atom_text(elems[0], source).as_deref() != Some("application") {
            continue;
        }
        let name = atom_text(elems[1], source)?;

        let mut version = AppVersion::Absent;
        let mut applications = Vec::new();
        if elems[2].kind() == "list" {
            for prop in named_children(elems[2]) {
                if prop.kind() != "tuple" {
                    continue;
                }
                let pair = named_children(prop);
                if pair.len() < 2 {
                    continue;
                }
                match atom_text(pair[0], source).as_deref() {
                    Some("vsn") => version = classify_vsn(pair[1], source),
                    Some("applications") if pair[1].kind() == "list" => {
                        applications = named_children(pair[1])
                            .into_iter()
                            .filter_map(|n| atom_text(n, source))
                            .collect();
                    }
                    _ => {}
                }
            }
        }

        return Some(ParsedAppSrc {
            name,
            version,
            applications,
        });
    }
    None
}

/// Classify a `vsn` value node into a manageable static version or a reason it is not.
fn classify_vsn(value: Node, source: &str) -> AppVersion {
    match value.kind() {
        "string" => match string_literal(value, source) {
            Some(literal) if literal.value == "git" => {
                AppVersion::Dynamic("its version is derived from git (`{vsn, \"git\"}`)")
            }
            Some(literal) if literal.value.contains('%') => AppVersion::Dynamic(
                "its version is a build-time template (e.g. `{vsn, \"%VSN%\"}`)",
            ),
            Some(literal) => AppVersion::Static(literal.value),
            None => AppVersion::Absent,
        },
        // `{vsn, git}` — the atom form of git-derived versioning.
        "atom" => AppVersion::Dynamic("its version is derived from git (`{vsn, git}`)"),
        _ => AppVersion::Dynamic("its version is not a literal string"),
    }
}

/// Locate the byte span of the `vsn` value when (and only when) it is a static string.
fn locate_vsn_string(source: &str) -> Option<StringLiteral> {
    let tree = parse_erlang(source)?;
    for tuple in top_level_tuples(&tree) {
        let elems = named_children(tuple);
        if elems.len() < 3 || atom_text(elems[0], source).as_deref() != Some("application") {
            continue;
        }
        if elems[2].kind() != "list" {
            continue;
        }
        for prop in named_children(elems[2]) {
            if prop.kind() != "tuple" {
                continue;
            }
            let pair = named_children(prop);
            if pair.len() >= 2 && atom_text(pair[0], source).as_deref() == Some("vsn") {
                return string_literal(pair[1], source);
            }
        }
    }
    None
}

/// Parse the entries of `{deps, [...]}` in a `rebar.config`. A dependency is either a
/// bare atom, `{name, "requirement"}`, or `{name, {source, ...}}` (path/git — no
/// registry requirement).
fn parse_rebar_deps(source: &str) -> Vec<ParsedDependency> {
    let Some(tree) = parse_erlang(source) else {
        return Vec::new();
    };
    let mut deps = Vec::new();
    for tuple in top_level_tuples(&tree) {
        let elems = named_children(tuple);
        if elems.len() < 2 || atom_text(elems[0], source).as_deref() != Some("deps") {
            continue;
        }
        if elems[1].kind() != "list" {
            continue;
        }
        for entry in named_children(elems[1]) {
            match entry.kind() {
                // `dep_name` with no options.
                "atom" => {
                    if let Some(name) = atom_text(entry, source) {
                        deps.push(ParsedDependency {
                            name,
                            requirement: None,
                        });
                    }
                }
                // `{dep_name, "req"}` or `{dep_name, {path, "..."}}`.
                "tuple" => {
                    let parts = named_children(entry);
                    let Some(name) = parts.first().and_then(|n| atom_text(*n, source)) else {
                        continue;
                    };
                    let requirement = parts
                        .get(1)
                        .and_then(|n| string_literal(*n, source))
                        .map(|literal| literal.value);
                    deps.push(ParsedDependency { name, requirement });
                }
                _ => {}
            }
        }
    }
    deps
}

fn warn_skip(name: &str, app_src: &Path, reason: &str) {
    eprintln!(
        "Warning: skipping '{}' ({}): {}; set a static `{{vsn, \"x.y.z\"}}` in the .app.src \
         for Sampo to manage it",
        name,
        app_src.display(),
        reason
    );
}

/// The `<name>.app.src.script` sibling of a `<name>.app.src`, if it exists.
fn script_sibling_exists(app_src: &Path) -> bool {
    let mut name = app_src
        .file_name()
        .map(|n| n.to_os_string())
        .unwrap_or_default();
    name.push(".script");
    app_src
        .parent()
        .map(|dir| dir.join(&name).exists())
        .unwrap_or(false)
}

fn is_app_src_file(path: &Path) -> bool {
    // `<name>.app.src.script` ends in `.script`, so it is naturally excluded.
    path.file_name()
        .and_then(|n| n.to_str())
        .map(|n| n.ends_with(APP_SRC_SUFFIX))
        .unwrap_or(false)
        && path.is_file()
}

/// The single `src/*.app.src` under `package_dir`, if any (the first, sorted, when a
/// directory unusually holds several).
fn find_app_src(package_dir: &Path) -> Option<PathBuf> {
    let mut candidates: Vec<PathBuf> = fs::read_dir(package_dir.join("src"))
        .ok()?
        .flatten()
        .map(|e| e.path())
        .filter(|p| is_app_src_file(p))
        .collect();
    candidates.sort();
    candidates.into_iter().next()
}

fn find_app_srcs(root: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    collect_app_srcs(root, 0, &mut out);
    out.sort();
    out
}

fn collect_app_srcs(dir: &Path, depth: usize, out: &mut Vec<PathBuf>) {
    if depth > MAX_SCAN_DEPTH {
        return;
    }

    // A directory with `mix.exs` is a Mix project (which may also carry generated
    // `.app.src` files); Mix owns its identity, so skip it here to avoid double-discovery.
    if !dir.join("mix.exs").exists()
        && let Some(app_src) = find_app_src(dir)
    {
        out.push(app_src);
    }

    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if !entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }
        if is_excluded_dir(&path) {
            continue;
        }
        collect_app_srcs(&path, depth + 1, out);
    }
}

/// Skip BEAM build output, fetched dependencies, and hidden directories so the scan
/// stays cheap and never treats a vendored `.app.src` as a workspace member.
fn is_excluded_dir(path: &Path) -> bool {
    match path.file_name().and_then(|n| n.to_str()) {
        Some(name) => {
            name.starts_with('.')
                || matches!(
                    name,
                    "_build" | "build" | "deps" | "node_modules" | "target"
                )
        }
        None => true,
    }
}

#[cfg(test)]
mod rebar3_tests;
