name: Publish After Merge

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write

jobs:
  publish:
    # Run only when a Release PR was merged into main
    if: >
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main' &&
      (
        startsWith(github.event.pull_request.head.ref, 'release/') ||
        contains(github.event.pull_request.title, 'Release')
      )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Publish crates (tag + publish)
        uses: bruits/sampo/crates/sampo-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          command: post-merge-publish
          cargo-token: ${{ secrets.CRATES_IO_TOKEN }}
          # Optional: also create GitHub Releases for new tags
          # create-github-release: true
          # Optional: pass flags to cargo publish
          # args: --allow-dirty --no-verify
