name: Release & Publish

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  discussions: write

jobs:
  build-artifacts:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # sampo CLI binaries
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            crate: sampo
            binary: sampo
          - os: macos-latest
            target: x86_64-apple-darwin
            crate: sampo
            binary: sampo
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            crate: sampo
            binary: sampo.exe
          # sampo-github-action binaries
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            crate: sampo-github-action
            binary: sampo-github-action
          - os: macos-latest
            target: x86_64-apple-darwin
            crate: sampo-github-action
            binary: sampo-github-action
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            crate: sampo-github-action
            binary: sampo-github-action.exe
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build release binary
        shell: bash
        run: |
          set -euo pipefail
          cargo build --release --bin ${{ matrix.crate }}
          mkdir -p dist/tmp
          cp "target/release/${{ matrix.binary }}" "dist/tmp/${{ matrix.binary }}"
          tar -C dist/tmp -czf "dist/${{ matrix.crate }}-${{ matrix.target }}.tar.gz" "${{ matrix.binary }}"
          rm -rf dist/tmp

      - name: Upload release binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.crate }}-${{ matrix.target }}
          path: dist/${{ matrix.crate }}-${{ matrix.target }}.tar.gz

  release:
    needs: build-artifacts
    runs-on: ubuntu-latest
    environment: sampo
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download release binaries
        uses: actions/download-artifact@v4
        with:
          pattern: "*"
          merge-multiple: true
          path: dist

      - name: Run Sampo to release & publish
        id: sampo
        uses: bruits/sampo/crates/sampo-github-action@main
        with:
          command: auto
          cargo-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          create-github-release: true
          release-assets: |
            dist/{{crate}}-x86_64-unknown-linux-gnu.tar.gz => {{crate}}-{{version}}-x86_64-unknown-linux-gnu.tar.gz
            dist/{{crate}}-x86_64-apple-darwin.tar.gz => {{crate}}-{{version}}-x86_64-apple-darwin.tar.gz
            dist/{{crate}}-x86_64-pc-windows-msvc.tar.gz => {{crate}}-{{version}}-x86_64-pc-windows-msvc.tar.gz
          open-discussion: true
          discussion-category: announcements
          use-local-build: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Check if sampo-github-bot was updated
        id: check-bot-update
        if: steps.sampo.outputs.published == 'true'
        env:
          GIT_PREVIOUS: ${{ github.event.before }}
        run: |
          set -euo pipefail
          PREV="${GIT_PREVIOUS}"
          if [ -z "$PREV" ] || [ "$PREV" = "0000000000000000000000000000000000000000" ]; then
            PREV=$(git rev-parse HEAD^ 2>/dev/null || echo "")
          fi

          if [ -n "$PREV" ]; then
            CHANGED=$(git diff --name-only "$PREV" HEAD)
          else
            CHANGED=$(git show --pretty="" --name-only HEAD)
          fi

          if printf '%s\n' "$CHANGED" | grep -q "^crates/sampo-github-bot/"; then
            echo "should-deploy=true" >> "$GITHUB_OUTPUT"
            echo "sampo-github-bot will be deployed"
          else
            echo "should-deploy=false" >> "$GITHUB_OUTPUT"
            echo "No sampo-github-bot changes detected"
          fi

      - name: Setup fly.io CLI
        if: steps.check-bot-update.outputs.should-deploy == 'true'
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy sampo-github-bot to fly.io
        if: steps.check-bot-update.outputs.should-deploy == 'true'
        working-directory: ./crates/sampo-github-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${FLY_API_TOKEN}" ]; then
            echo "Warning: FLY_API_TOKEN secret not configured. Skipping deployment."
            echo "To enable automatic deployment, add FLY_API_TOKEN to repository secrets."
            exit 0
          fi

          echo "Deploying sampo-github-bot to fly.io..."
          flyctl deploy --remote-only
